// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/api/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSupports implements SupportInterface
type FakeSupports struct {
	Fake *FakeOperatorV1alpha1
}

var supportsResource = schema.GroupVersionResource{Group: "operator.openshift.io", Version: "v1alpha1", Resource: "supports"}

var supportsKind = schema.GroupVersionKind{Group: "operator.openshift.io", Version: "v1alpha1", Kind: "Support"}

// Get takes name of the support, and returns the corresponding support object, and an error if there is any.
func (c *FakeSupports) Get(name string, options v1.GetOptions) (result *v1alpha1.Support, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(supportsResource, name), &v1alpha1.Support{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Support), err
}

// List takes label and field selectors, and returns the list of Supports that match those selectors.
func (c *FakeSupports) List(opts v1.ListOptions) (result *v1alpha1.SupportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(supportsResource, supportsKind, opts), &v1alpha1.SupportList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SupportList{ListMeta: obj.(*v1alpha1.SupportList).ListMeta}
	for _, item := range obj.(*v1alpha1.SupportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested supports.
func (c *FakeSupports) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(supportsResource, opts))
}

// Create takes the representation of a support and creates it.  Returns the server's representation of the support, and an error, if there is any.
func (c *FakeSupports) Create(support *v1alpha1.Support) (result *v1alpha1.Support, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(supportsResource, support), &v1alpha1.Support{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Support), err
}

// Update takes the representation of a support and updates it. Returns the server's representation of the support, and an error, if there is any.
func (c *FakeSupports) Update(support *v1alpha1.Support) (result *v1alpha1.Support, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(supportsResource, support), &v1alpha1.Support{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Support), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSupports) UpdateStatus(support *v1alpha1.Support) (*v1alpha1.Support, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(supportsResource, "status", support), &v1alpha1.Support{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Support), err
}

// Delete takes name of the support and deletes it. Returns an error if one occurs.
func (c *FakeSupports) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(supportsResource, name), &v1alpha1.Support{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSupports) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(supportsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SupportList{})
	return err
}

// Patch applies the patch and returns the patched support.
func (c *FakeSupports) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Support, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(supportsResource, name, pt, data, subresources...), &v1alpha1.Support{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Support), err
}
